{% set name = "mmcif_pdbx" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e37268046e15b2a348aa2298cdba79ae2dae3f43e0a0b0ddd46066a681410811

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - pdbx

about:
  home: https://github.com/Electrostatics/mmcif_pdbx
  license: CC0
  license_family: PUBLIC-DOMAIN
  license_file: LICENSE
  summary: Python utilities for PDBx/mmCIF storage model
  doc_url: http://mmcif.wwpdb.org/pdbx-mmcif-home-page.html
  dev_url: https://github.com/Electrostatics/mmcif_pdbx

extra:
  recipe-maintainers:
    - sobolevnrm
    - tsenapathi
